# version: "3.4"
services:
  vite_docker:
    image: sth123/gamedesign3frontend:latest
    container_name: gamedesign3.school.tygo.van.den.hurk.dev-vite
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - ./:/srv/app
    tty: true
