version: "3.8"

# Use the following command:
#
#   docker compose up -d --build 
#
# to start the container.

services:
  frontend:
    container_name: gamedesign3.school.tygo.van.den.hurk.dev-vite
    build: 
      dockerfile: Dockerfile
    # image: .
    restart: always
    # entrypoint: /bin/sh
    networks:
      - 'proxymesh'
      - 'default'
    ports:
      - 4173:4173
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    tty: true

networks:
  proxymesh:
    external: true